---
title: "Homework"
subtitle: "Quarto Template<br><br>" 
date: "`r Sys.Date(Dec 5th 2023)`"

format: 
  html:
    toc: true
    number-sections: true
    code-fold: false       # https://quarto.org/docs/output-formats/html-code.html
    code-summary: "Show the code"
    code-tools: true
    highlight-style: tango # atom-one tango espresso

execute: 
  echo: true
  eval: true
  warning: false
  message: false
  fig-width: 9
  
---

# SUNY Geneseo, Fall 2023
# DANL 200: Introduction to Data Analytics
# Homework Assignment 1

# Instructor: Byeong-Hak Choe
# Student Name: Jake Marcell
# Student ID: G00802384
# List of students whom you work with:
  # Jake Knapp
  # Blaise Leone
  # Mac Bean
  # Sophie Rodger



# Question 2. Working with starwars data.frame -----------------------------


# Q2a --------------------------------------------------------------

# Download the CSV file, starwars.csv, 
# from the Brightspace. 

# Read the data file, starwars.csv, 
# as the data.frame object with the name, 
# starwars, using (1) the read_csv() function and 
# (2) the absolute path name of the file starwars.csv
# from your local hard disk drive in your laptop.

# Answer for Q2a

library(readr)
starwars <- read_csv("/Users/jakemarcell/Downloads/starwars.csv")



# Variable Description for starwars ---------------------------------------

# The following describes the variables 
# in the `starwars` data.frame.

# films: List of films the character appeared in
# name: Name of the character
# species: Name of species
# height: Height (cm)
# mass: Weight (kg)
# hair_color, skin_color, eye_color: Hair, skin, and eye colors
# birth_year: Year born (BBY = Before Battle of Yavin)
# sex: The biological sex of the character, 
# namely male, female, hermaphroditic, or none (as in the case for Droids).
# gender: The gender role or gender identity of the character 
# as determined by their personality or 
# the way they were programmed (as in the case for Droids).
# homeworld: Name of homeworld


# Q2b --------------------------------------------------------------
# Provide the R code to find how many characters are 
# `Droid` `species`.

# Answer for Q2b

droid_count <- sum(starwars$species == "Droid", na.rm = T)


# Q2c --------------------------------------------------------------
# Provide the R code to find which `Droid` character did appear 
# most in the Star Wars `films`.

# Answer for Q2c

droid_appearances <- table(starwars$name[starwars$species == "Droid"])
droid_appearances
most_appearances <- names(droid_appearances)[which.max(droid_appearances)]


# Q2d --------------------------------------------------------------
# Provide the R code to find the minimum, first quartile, 
# median, third quartile, and the maximum of `height`.

# [Statistics] Explain why the median value is different from 
# the mean value.
# When is the median value greater than the mean value?
# When is the median value less than the mean value?

# Answer for Q2d


height_summary <- summary(starwars$height)

min_height <- height_summary[1]
min_height
q1_height <- height_summary[2]
q1_height
median_height <- height_summary[3]
median_height
q3_height <- height_summary[4]
q3_height
max_height <- height_summary[5]
max_height

# Q2e --------------------------------------------------------------
# Provide the R code to find the number of unique/distinct 
# `homeworld` values.

# Answer for Q2e

unique_homeworlds <- length(unique(starwars$homeworld))


# Question 3. Data Visualization with gapminder ----------------------------


# Q3a ---------------------------------------------------------------------
# Provide the R code to install the R package, `gapminder`.

# Answer for Q3a

install.packages("gapminder")

# Q3b ---------------------------------------------------------------------
# Load the `gapminder` data.frame provided by the R package, 
# `gapminder`.

# Answer for Q3b

library(gapminder)
data(gapminder)


# Variable Description for gapminder data.frame ------------------------------

# The following describe the variables in the `gapminder` data.frame.

# `country`
# factor with 142 levels

# `continent`
# factor with 5 levels

# `year`
# ranges from 1952 to 2007 in increments of 5 years

# `lifeExp`
# life expectancy at birth, in years

# `pop`
# population

# `gdpPercap`
# GDP per capita (US$, inflation-adjusted)




# Q3c ---------------------------------------------------------------------

# Provide ggplot code and comments to describe 
# the relationship between `gdpPercap` and `lifeExp`.

# Answer for Q3c

library(ggplot2)
ggplot(gapminder, aes(x = gdpPercap, y = lifeExp)) +
  geom_point() +
  labs(x = "GDP per Capita", y = "Life Expectancy") +
  ggtitle("Relationship between GDP per Capita and Life Expectancy")

# The scatter plot shows the relationship between GDP per Capita and Life Expectancy.
# Generally, there is a positive correlation between these two variables, indicating that
# countries with higher GDP per Capita tend to have higher life expectancy.

# Q3d ---------------------------------------------------------------------

# Provide ggplot code and comments to describe 
# how the relationship between `gdpPercap` and `lifeExp` 
# varies by `continent`.

# Answer for Q3d

ggplot(gapminder, aes(x = gdpPercap, y = lifeExp, color = continent)) +
  geom_point() +
  labs(x = "GDP per Capita", y = "Life Expectancy", color = "Continent") +
  ggtitle("Relationship between GDP per Capita and Life Expectancy by Continent")

# This scatter plot shows the relationship between GDP per Capita and Life Expectancy
# for different continents, represented by different colors. It allows us to see how
# this relationship varies by continent. We can observe that the positive correlation
# between GDP per Capita and Life Expectancy holds for most continents, although there
# are variations in the strength of the correlation and some outliers.

# -----------------------------------------------------------------------
